/*
    see comment in OSGCOMUD.h

    This file is automatically generated by the build system,
    which tries to know what options are valid in what
    combinations. Avoid changing this file manually unless
    you know what you're doing.
*/


#define RomFileName "Mac128K.ROM"
#define kCheckSumRom_Size 0x00010000
#define kRomCheckSum1 0x28BA61CE
#define kRomCheckSum2 0x28BA4E50
#define RomStartCheckSum 1
#define SaveDialogEnable 1
#define EnableAltKeysMode 0
#define VarFullScreen 1
#define WantInitFullScreen 0
#define MayFullScreen 1
#define MayNotFullScreen 1
#define WantInitMagnify 0
#define EnableMagnify 1
#define MyWindowScale 2
#define WantInitRunInBackground 0
#define WantInitNotAutoSlow 0
#define WantInitSpeedValue 3
#define WantEnblCtrlInt 1
#define WantEnblCtrlRst 1
#define WantEnblCtrlKtg 1
#define UseControlKeys 1
#define UseActvCode 0
#define EnableDemoMsg 0
