/*
    see comment in OSGCOMUD.h

    This file is automatically generated by the build system,
    which tries to know what options are valid in what
    combinations. Avoid changing this file manually unless
    you know what you're doing.
*/

#define MySoundEnabled 1

#define MySoundRecenterSilence 0
#define kLn2SoundSampSz 3

#define dbglog_HAVE 0
#define WantAbnormalReports 0

#define NumDrives 2
#define NonDiskProtect 0
#define IncludeSonyRawMode 1
#define IncludeSonyGetName 1
#define IncludeSonyNew 1
#define IncludeSonyNameNew 1

#define vMacScreenHeight 342
#define vMacScreenWidth 512
#define vMacScreenDepth 0

#define kROM_Size 0x00010000

#define IncludePbufs 1
#define NumPbufs 4

#define EnableMouseMotion 1

#define IncludeHostTextClipExchange 1
#define EnableAutoSlow 1
#define EmLocalTalk 0
#define AutoLocation 1
#define AutoTimeZone 1

#ifdef PLIST_PREPROCESSOR
#define MNVMBundleDisplayName Mac 128K
#define MNVMBundleGetInfoString 128K, 512×342
#endif
