/*
    see comment in OSGCOMUI.h

    This file is automatically generated by the build system,
    which tries to know what options are valid in what
    combinations. Avoid changing this file manually unless
    you know what you're doing.
*/


#import <Foundation/Foundation.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/param.h>
#include <sys/time.h>
